compression:
  name: Qwen/Qwen2.5-0.5B-Instruct
  revision: 7ae557604adf67be50417f59c2c2f167def9a775
  dtype: bfloat16
  batch_dimension: 1
  use_cache: false
downstream:
  name: Qwen/Qwen2.5-7B-Instruct
  revision: a09a35458c702b33eeacc393d103063234e8bc28

